server:
  port: 9090


jwt:
  secret-key : "jwt-secret-key"
  time: 30

oauth2:
  providers:
    google:
      client-id : ""
      client-secret : ""
      redirect-uri : ""
    github:
      client-id: ""
      client-secret: ""
      redirect-uri: ""

database:
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 0
    timeout: 10000
  redisson:
    host: redis://127.0.0.1:6379
    timeout: 10000
    password: ""

  mysql:
    url: jdbc:mysql://localhost:3306/bank?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver



spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect